[package]
name = "blip"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
uefi = { version =  "0.35.0", features = ["alloc","global_allocator","panic_handler","logger"] }
log = "0.4.27"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'